MODEL:
  DEVICE: "cuda"
  NAME: 'cosine_baseline'
  BACKBONE: 'resnet50_ibn_a'
  LAST_STRIDE: 1
  LABEL_SMOOTH: False
  USE_DROPOUT: False
  PRETRAIN_PATH: '../weights/models/r50_ibn_a.pth'
  USE_COS: True
  BASELINE:
    POOL_TYPE: 'avg'
    TPL_WEIGHT: 0.9
    CE_WEIGHT: 0.1
    COSINE_LOSS_TYPE: 'ArcFace'
    S: 30.0
    M: 0.5

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  RE_MAX_RATIO: 0.2
  PADDING: 10
  PIXEL_MEAN: [0.1646,0.2110,0.2467]
  PIXEL_STD: [0.1366,0.1373,0.1806]
  NORMALIZATION: True
  SEPNORM:
    USE: False
    PIXEL_MEAN: [[0.1164,0.1567,0.1796],[0.4556,0.5367,0.6493]]
    PIXEL_STD: [[0.1467,0.1497,0.1930],[0.0750,0.0613,0.1040]]
    TEST_PIXEL_MEAN: [[0.1164,0.1567,0.1796],[0.5410,0.4631,0.5808]]
    TEST_PIXEL_STD: [[0.1467,0.1497,0.1930],[0.0444,0.0821,0.0981]]
DATASETS:
  NAMES: ('competition')
  DATA_PATH: '/share/Dataset/PReID/all_dataset/'
  TRAIN_PATH: 'rep_f0_train'
  QUERY_PATH: 'rep_f0_query'
  GALLERY_PATH: 'rep_f0_gallery'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 6

SOLVER:
  OPTIMIZER_NAME: "Adam"
  FP16: False
  SYNCBN: False

  BASE_LR: 3e-4
  BIAS_LR_FACTOR: 1

  MOMENTUM: 0.9

  MARGIN: 0.3

  WEIGHT_DECAY: 5e-4
  WEIGHT_DECAY_BIAS: 5e-4

  GAMMA: 0.1
  STEPS: [40, 70]

  WARMUP_FACTOR: 0.01 
  WARMUP_EPOCH: 10
  WARMUP_BEGAIN_LR: 3e-05
  WARMUP_METHOD: "linear"

  MAX_EPOCHS: 120
  CHECKPOINT_PERIOD: 2
  LOG_PERIOD: 100
  EVAL_PERIOD: 2
  START_SAVE_EPOCH: 80

  IMS_PER_BATCH: 64
  TENSORBOARD: 
    USE: True
    LOG_PERIOD: 20
TEST:
  IMS_PER_BATCH: 64
  WEIGHT: ""
  DEBUG: False
  MULTI_GPU: False
  CMC: [1,5,10]
  VIS: False
  VIS_Q_NUM: 10
  VIS_G_NUM: 5
  RERANK: False
  RANDOMPERM: 5 # [fix]

OUTPUT_DIR: "../work_dirs/baseline/"


